In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

In [13]:
# read csv dataset
dataset = {}
for i in range(17,24):
    dataset["Y20"+str(i)] = pd.read_csv('FIFA'+str(i)+'_official_data.csv')

In [14]:
# tidy up dataset
dataset["Y2023"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17660 entries, 0 to 17659
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        17660 non-null  int64
 1   Name                      17660 non-null  object
 2   Age                       17660 non-null  int64
 3   Photo                     17660 non-null  object
 4   Nationality               17660 non-null  object
 5   Flag                      17660 non-null  object
 6   Overall                   17660 non-null  int64
 7   Potential                 17660 non-null  int64
 8   Club                      17449 non-null  object
 9   Club Logo                 17660 non-null  object
 10  Value                     17660 non-null  object
 11  Wage                      17660 non-null  object
 12  Special                   17660 non-null  int64
 13  Preferred Foot            17660 non-null  object
 14  International Reputation  17660 non-null  float64
 15  Weak Foot                 17660 non-null  float64
 16  Skill Moves               17660 non-null  float64
 17  Work Rate                 17660 non-null  object
 18  Body Type                 17622 non-null  object
 19  Real Face                 17622 non-null  object
 20  Position                  17625 non-null  object
 21  Joined                    16562 non-null  object
 22  Loaned From               694 non-null    object
 23  Contract Valid Until      17299 non-null  object
 24  Height                    17660 non-null  object
 25  Weight                    17660 non-null  object
 26  Release Clause            16509 non-null  object
 27  Kit Number                17625 non-null  float64
 28  Best Overall Rating       21 non-null     object
dtypes: float64(4), int64(5), object(20)
memory usage: 3.9+ MB

In [15]:
dataset["Y2023"].head(10)

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Real Face,Position,Joined,Loaned From,Contract Valid Until,Height,Weight,Release Clause,Kit Number,Best Overall Rating
0,209658,L. Goretzka,27,https://cdn.sofifa.net/players/209/658/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,87,88,FC Bayern München,https://cdn.sofifa.net/teams/21/30.png,...,Yes,"<span class=""pos pos28"">SUB","Jul 1, 2018",NaN,2026,189cm,82kg,€157M,8.0,NaN
1,212198,Bruno Fernandes,27,https://cdn.sofifa.net/players/212/198/23_60.png,Portugal,https://cdn.sofifa.net/flags/pt.png,86,87,Manchester United,https://cdn.sofifa.net/teams/11/30.png,...,Yes,"<span class=""pos pos15"">LCM","Jan 30, 2020",NaN,2026,179cm,69kg,€155M,8.0,NaN
2,224334,M. Acuña,30,https://cdn.sofifa.net/players/224/334/23_60.png,Argentina,https://cdn.sofifa.net/flags/ar.png,85,85,Sevilla FC,https://cdn.sofifa.net/teams/481/30.png,...,No,"<span class=""pos pos7"">LB","Sep 14, 2020",NaN,2024,172cm,69kg,€97.7M,19.0,NaN
3,192985,K. De Bruyne,31,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,https://cdn.sofifa.net/flags/be.png,91,91,Manchester City,https://cdn.sofifa.net/teams/10/30.png,...,Yes,"<span class=""pos pos13"">RCM","Aug 30, 2015",NaN,2025,181cm,70kg,€198.9M,17.0,NaN
4,224232,N. Barella,25,https://cdn.sofifa.net/players/224/232/23_60.png,Italy,https://cdn.sofifa.net/flags/it.png,86,89,Inter,https://cdn.sofifa.net/teams/44/30.png,...,Yes,"<span class=""pos pos13"">RCM","Sep 1, 2020",NaN,2026,172cm,68kg,€154.4M,23.0,NaN
5,212622,J. Kimmich,27,https://cdn.sofifa.net/players/212/622/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,89,90,FC Bayern München,https://cdn.sofifa.net/teams/21/30.png,...,Yes,"<span class=""pos pos9"">RDM","Jul 1, 2015",NaN,2025,177cm,75kg,€182M,6.0,NaN
6,197445,D. Alaba,30,https://cdn.sofifa.net/players/197/445/23_60.png,Austria,https://cdn.sofifa.net/flags/at.png,86,86,Real Madrid CF,https://cdn.sofifa.net/teams/243/30.png,...,Yes,"<span class=""pos pos6"">LCB","Jul 1, 2021",NaN,2026,180cm,78kg,€113.8M,4.0,NaN
7,187961,22 Paulinho,32,https://cdn.sofifa.net/players/187/961/22_60.png,Brazil,https://cdn.sofifa.net/flags/br.png,83,83,Al Ahli,https://cdn.sofifa.net/teams/112387/30.png,...,Yes,"<span class=""pos pos15"">LCM","Jul 22, 2021",NaN,2024,183cm,80kg,€48.5M,15.0,NaN
8,208333,E. Can,28,https://cdn.sofifa.net/players/208/333/23_60.png,Germany,https://cdn.sofifa.net/flags/de.png,82,82,Borussia Dortmund,https://cdn.sofifa.net/teams/22/30.png,...,Yes,"<span class=""pos pos28"">SUB","Feb 18, 2020",NaN,2024,186cm,86kg,€51.9M,23.0,NaN
9,210514,João Cancelo,28,https://cdn.sofifa.net/players/210/514/23_60.png,Portugal,https://cdn.sofifa.net/flags/pt.png,88,88,Manchester City,https://cdn.sofifa.net/teams/10/30.png,...,Yes,"<span class=""pos pos7"">LB","Aug 7, 2019",NaN,2027,182cm,74kg,€152.6M,7.0,NaN

In [16]:
print(dataset['Y2023'].columns.values)

['ID' 'Name' 'Age' 'Photo' 'Nationality' 'Flag' 'Overall' 'Potential'
 'Club' 'Club Logo' 'Value' 'Wage' 'Special' 'Preferred Foot'
 'International Reputation' 'Weak Foot' 'Skill Moves' 'Work Rate'
 'Body Type' 'Real Face' 'Position' 'Joined' 'Loaned From'
 'Contract Valid Until' 'Height' 'Weight' 'Release Clause' 'Kit Number'
 'Best Overall Rating']

In [17]:
columns_to_drop = ['ID','Nationality', 'Flag', 'Club Logo', 'International Reputation','Real Face','Loaned From', 'Contract Valid Until']
for i in range(17,24):
    dataset['Y20'+str(i)] = dataset['Y20'+str(i)].drop(columns=columns_to_drop,axis=1)
dataset["Y2023"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17660 entries, 0 to 17659
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 17660 non-null  object
 1   Age                  17660 non-null  int64
 2   Photo                17660 non-null  object
 3   Overall              17660 non-null  int64
 4   Potential            17660 non-null  int64
 5   Club                 17449 non-null  object
 6   Value                17660 non-null  object
 7   Wage                 17660 non-null  object
 8   Special              17660 non-null  int64
 9   Preferred Foot       17660 non-null  object
 10  Weak Foot            17660 non-null  float64
 11  Skill Moves          17660 non-null  float64
 12  Work Rate            17660 non-null  object
 13  Body Type            17622 non-null  object
 14  Position             17625 non-null  object
 15  Joined               16562 non-null  object
 16  Height               17660 non-null  object
 17  Weight               17660 non-null  object
 18  Release Clause       16509 non-null  object
 19  Kit Number           17625 non-null  float64
 20  Best Overall Rating  21 non-null     object
dtypes: float64(3), int64(4), object(14)
memory usage: 2.8+ MB

In [18]:
dataset['Y2023'].describe()

,Age,Overall,Potential,Special,Weak Foot,Skill Moves,Kit Number
count,17660.000000,17660.000000,17660.000000,17660.000000,17660.000000,17660.000000,17625.000000
mean,23.127746,63.369592,70.981200,1537.915855,2.900340,2.297169,25.037957
std,4.639821,8.036268,6.529836,285.893809,0.663523,0.754264,19.154116
min,15.000000,43.000000,42.000000,749.000000,1.000000,1.000000,1.000000
25%,20.000000,58.000000,67.000000,1387.000000,3.000000,2.000000,11.000000
50%,22.000000,63.000000,71.000000,1548.000000,3.000000,2.000000,22.000000
75%,26.000000,69.000000,75.000000,1727.000000,3.000000,3.000000,32.000000
max,54.000000,91.000000,95.000000,2312.000000,5.000000,5.000000,99.000000

In [19]:
# visualize
df23 = dataset['Y2023']

In [20]:
sort50_df23 = df23.sort_values(by='Overall', ascending=False).head(50)

In [ ]:
fix, ax = plt.subplots(figsize=(15,15))
sns.set_theme(style='whitegrid')
ax = sns.barplot(x='Name', y= 'Overall', data = sort_df23)
plot.show()